### ISSUE TITLE
fails to import

### ISSUE THREAD

**Issue by Mabeloid** [zachary822/chinese-converter#3]
```
Traceback (most recent call last):
  File "[...].py", line 1, in <module>
    import chinese_converter
  File "[...]\site-packages\chinese_converter\__init__.py", line 12, in <module>
    traditional, simplified = f.read().strip(), g.read().strip()
UnicodeDecodeError: 'cp932' codec can't decode byte 0x84 in position 71: illegal multibyte sequence
```

**Comment by zachary822** [comment]
new release is live. update to v1.1.0.
